name: Convert Markdown to HTML

on:
  push:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Pandoc
      run: |
        sudo apt-get install -y pandoc

    - name: Convert Markdown to HTML
      run: |
        for markdown in $(find . -name '*.md'); do
            pandoc $markdown -o ${markdown%.md}.html
        done

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Convert Markdown files to HTML" || echo "No changes to commit"
        git push origin HEAD:<branch_name>  # replace <branch_name> with the name of your branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
